"""Update models to use BaseModel and fix foreign keys

Revision ID: 631ec200532a
Revises: e2436d1355a7
Create Date: 2025-04-04 10:00:50.733281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631ec200532a'
down_revision = 'e2436d1355a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shopify_product_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimized_descriptions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('optimized_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'DEPLOYED', name='descriptionstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registered')
        batch_op.drop_column('is_active')
        batch_op.drop_column('name')

    op.drop_table('optimized_descriptions')
    op.drop_table('products')
    # ### end Alembic commands ###
