"""Update Product model with additional Shopify fields

Revision ID: 9a6c40f543e5
Revises: dd9073d421e1
Create Date: 2025-04-04 14:24:52.194881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6c40f543e5'
down_revision = 'dd9073d421e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('product_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('handle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shopify_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shopify_updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('original_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_description', sa.TEXT(), nullable=True))
        batch_op.drop_column('shopify_updated_at')
        batch_op.drop_column('shopify_created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('handle')
        batch_op.drop_column('product_type')
        batch_op.drop_column('vendor')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
