"""Add original_description to OptimizedDescription model

Revision ID: b3b9866b437b
Revises: 9a6c40f543e5
Create Date: 2025-04-04 14:28:45.344989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b9866b437b'
down_revision = '9a6c40f543e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimized_descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimized_descriptions', schema=None) as batch_op:
        batch_op.drop_column('original_description')

    # ### end Alembic commands ###
